# Generated by Django 6.0.7 on 2026-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mle_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
