# Generated by Django 5.0.14 on 2026-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_mle_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='statut',
            field=models.CharField(choices=[('Present', 'Présent'), ('Absent', 'Absent'), ('Repos', 'Repos'), ('Ferie', 'Férié')], max_length=20),
        ),
    ]
