# Generated by Django 4.2 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publicholiday_alter_attendance_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='disabled_families',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
